# Generated by Django 4.1.7 on 2023-03-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL')),
                ('named_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Named URL')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childes', to='menu.menu')),
            ],
            options={
                'verbose_name': 'Menu',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='HeadMenu',
            fields=[
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='head', serialize=False, to='menu.menu')),
                ('title', models.SlugField(verbose_name='Title')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menus', to='menu.headmenu'),
        ),
    ]
